build.sbt, project/plugins.sbt
This PR adds setting for distribution of projects on Sonatype.
@dialelo @raulraja Could you take a look please? Thank you.
=> Adds settings for distributing projects in Sonatype

src/main/scala/stdlib/Asserts.scala, src/test/scala/exercises/stdlib/AssertsSpec.scala
@rafaparadela plz take a look.
=> Fix exercise

src/main/scala/stdlib/Options.scala, src/test/scala/exercises/stdlib/OptionsSpec.scala
Problem
Test in the options exercise throws an error because the test expects a Float instead of a Double from the user
Solution
Change type of argument to Doube
=> Options type error (Issue #13)

src/main/scala/stdlib/TypeSignatures.scala
The website still needs to be fixed - there is a compilation error: deriveMetaInformationTypeSignatures cannot be completed due to "not enough arguments". (Exercise 30: Type Signatures, case 3)
=> fix unused parameter

src/main/scala/stdlib/Lists.scala, src/test/scala/exercises/stdlib/ListsSpec.scala
Based on the work by @idarlington
=> Fix reuse list tail exercise

src/main/scala/stdlib/Maps.scala, src/test/scala/exercises/stdlib/MapSpec.scala
This case demonstrates the behavior of attempting to call myMap(missingKey) in that an exception is thrown. It also provides examples of how to handle this gracefully using default values via either getOrElse or for the entire map with withDefaultValue. Also included corresponding test case.
=> Adding additional test case to Std Lib Maps

src/main/scala/stdlib/Traversables.scala
foldRight shorthand example is duplicated
=> Traversable foldRight verbose example is missing

src/main/scala/stdlib/Asserts.scala, src/main/scala/stdlib/CaseClasses.scala
=> Minor syntactic fixes

src/main/scala/stdlib/Extractors.scala
1. wrap code in `{{{ }}}`s
2. fix list items from `*` to `-`
=> Extractors chapter - markdown fixes

src/main/scala/stdlib/Implicits.scala, src/test/scala/stdlib/ImplicitsSpec.scala
1. Fix markdown list at line 11
2. Add code backticks to some terms
3. Some edits (colons and capitalizing Implicit Function Parameters) for consistency w/ rest of doc
4. On line 105 
```diff
-def asDefaultImplicits(res0: Float) {
+def asDefaultImplicits(res0: BigDecimal) {
```
Since, I had to manually cast the answer on the koan to Float. IDK if this requires a change on somewhere else in the code, but can do it if you point me to the file.
=> Implicits Chapter: Edits to docstrings, plus one code change

src/main/scala/stdlib/Iterables.scala
In the Iterables section, under `grouped` the word "an" makes this sentence confusing
=> Fix grammar of `grouped` description

src/main/scala/stdlib/Objects.scala
Make more clear that the term "object" at the end of the sentence does not refer to the same "object" as in the beginnig of the sentence.
=> Small textual change for clarity.

src/main/scala/stdlib/ByNameParameter.scala
The comment "//An explicit call the x function" is grammatically incomplete.
=> Small textual change / Grammar

src/main/scala/stdlib/CaseClasses.scala
`print` is sometimes called, and sometimes it is `Console.print`. I removed `Console.` to make the calls all the same.
=> Make the calls to print/println uniform

src/main/scala/stdlib/Implicits.scala, src/test/scala/stdlib/ImplicitsSpec.scala
Seeing `BigDecimal(34.00).toString()` makes the programmer guess if the answer is `34`, `34.0` or `34.00`. Maybe it's simpler to have them all as `Integer` instead of `Double` and avoid the confusion.
=> Uses Integer values when creating BigDecimal values to avoid the decimal point when calling toString

src/main/scala/stdlib/HigherOrderFunctions.scala
Also fixing the previous question so that the description is before the actual code.
=> Adding closure documentation

src/main/scala/stdlib/Objects.scala, src/test/scala/stdlib/ObjectsSpec.scala
Having 4 examples which are solved by copy & paste is tiring
=> Removed superfluous repetition

src/main/scala/stdlib/Traversables.scala
In foldRightFunctionTraversables explanation, foldRight is not quoted correctly and the rest of phrase is rendered as code.
=> Fix foldRight code quote

src/main/scala/stdlib/Maps.scala, src/main/scala/stdlib/PatternMatching.scala, src/main/scala/stdlib/Traversables.scala, src/test/scala/stdlib/MapsSpec.scala, src/test/scala/stdlib/PatternMatchingSpec.scala
Changed wording on unique Map entries, moved access example
=> minor fixes in Maps

src/main/scala/stdlib/Options.scala
Using `noNumber.fold(0)(_ * 3)` makes it unclear whether or not the default value goes through the same process. In other words, is the result 0 because that's the value we provide, or because `0 = 0 * 3`?
Using `val result2 = noNumber.fold(1)(_ * 3)` makes it clearer, as the result is 1 and not 3.
=> Update Options.scala to improve clarity with option folding

src/main/scala/stdlib/Ranges.scala
Changed some of the language and syntax used in the introduction of the "Ranges" section for more accuracy and clarity.
=> Clarify introduction to "Ranges"

src/main/scala/stdlib/TypeSignatures.scala, src/test/scala/stdlib/TypeSignaturesSpec.scala
The exercise description says that `isInstanceOf[className]` is used to determine if an object reference is an instance of a given class, but it doesn't currently verify the most basic checks.
=> Expand the type signatures exercise with instanceof checks for a class and a trait

src/main/scala/stdlib/SequencesandArrays.scala, src/test/scala/stdlib/SequencesAndArraysSpec.scala
If you try to compile with List[String] you receive type mismatch error:
"Error:() type mismatch;
found   : Seq[String]
required: List[String]
val r: List[String] = s map {"
=> Sequences And Arrays: Change type of res0: from List to Seq

src/main/scala/stdlib/Traversables.scala, src/test/scala/stdlib/TraversablesSpec.scala
The `performantTraversables` exercise has three problems:
1. It is not deterministic. People report (and I experienced it myself) that the result is sometime `true` and sometimes `false`.
2. You should not benchmark method calls like this. The JVM needs to warm up, there are a lot of optimizations going on. Use a microbenchmarking framework.
3. The comment states that you might receive a `StackOverflowError`. This is not true, as `reduceRight` is implemented based on `reduceLeft`, making it also tail recursive if `reduceLeft` is tail recursive.
I suggest to replace the exercise with another one demonstrating the relationship between the left and the right operation. The new exercise is deterministic. Also I removed the wrong comment about the `StackOverflowError`.
=> Replace nondeterministic performantTraversables

src/main/scala/stdlib/Options.scala
Just a little tweak to make it clearer to beginners that `getOrElse` will return the wrapped value if the `Option` is a `Some`, and the provided default value if it is `None` (since there seemed to be some confusion in the comments on this section).
=> Clarify the purpose of getOrElse

src/main/scala/stdlib/NamedandDefaultArguments.scala
small typo fixed, it's better undestood now I think.
=> typo fixed functional -> functions

src/main/scala/stdlib/Traits.scala
Increased explanation about java's default methods in interfaces
=> Java do have default methods in interfaces.

.travis.yml, build.sbt, project/ProjectPlugin.scala, project/build.properties, src/main/scala/stdlib/HigherOrderFunctions.scala, src/main/scala/stdlib/Ranges.scala, src/main/scala/stdlib/Traits.scala, src/main/scala/stdlib/Traversables.scala, version.sbt
This PR excludes monix from the classpath in the exercises, since it's not needed. It also bumps scala up.
It'll release a new minor snapshot release.
=> Adds minor upgrade to stdlib exercises

src/main/scala/stdlib/NamedandDefaultArguments.scala
I also removed a comment line that appeared to be an instruction for building the interactive example.
=> Fix wording in NamedandDefaultArguments.scala

src/main/scala/stdlib/Extractors.scala
Please do sanity check my change here - have I misread the sentence?
`unapplySeq` is useful when the number of sub-values **isn't** fixed, right?
=> unapplySeq is useful when number of subvalues ISN'T fixed

src/main/scala/stdlib/Iterables.scala
See https://stackoverflow.com/questions/29008500/scala-sets-contain-the-same-elements-but-sameelements-returns-false
=> Explain that sameElements will work differently for a small set

.scalafmt.conf, src/main/scala/stdlib/Asserts.scala, src/main/scala/stdlib/Iterables.scala, src/main/scala/stdlib/Options.scala
=> Update scalafmt-core to 2.6.1

src/main/scala/stdlib/CaseClasses.scala
error: recursive method printTerm needs result type
error: not found: type Application
warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method println, or remove the empty argument list from its definition (Java-defined methods are exempt). In Scala 3, an unapplied method like this will be eta-expanded into a function.
=> fixed compilation errors and warnings

src/main/scala/stdlib/LiteralNumbers.scala, src/test/scala/stdlib/LiteralNumbersSpec.scala
Hello, I've noticed that PR #169 seems to have introduced a minor error in Literal Numbers: previously, the values in the Float section looked like this:
```scala
val a = 3.0
val b = 3.00
val c = 2.73
val d = 3f
val e = 3.22d
val f = 93e-9
val g = 93E-9
val h = 0.0
val i = 9.23E-9D
```
This version used both `93e-9` and `93E-9`, to demonstrate that both are acceptable ways of representing the exponent. Furthermore, `i` used `9.23E-9D`, to show that uppercase double literals work. But after #169, it looks like this:
```scala
val a = 3.0
val b = 3.00
val c = 2.73
val d = 3f
val e = 3.22d
val f = 93e-9
val g = 93e-9
val h = 0.0
val i = 9.23e-9d
```
In this version, both `f` and `g` are the same: `93e-9`, and `i` has been swapped to lowercase. Unless I'm mistaken, this was probably not what's …
=> Correct a minor regression in Literal Numbers: remove duplicate exercise 'g' from LiteralNumbers (Floats section)

src/main/scala/stdlib/Formatting.scala
correct answer based on this app:
but the real result should be:
```
"%c".format(e)                                                                                                     
val res18: String = "
scala> "%c".format(f)                                                                                                     
val res19: String = \
```
This is misleading (thanks to character escaping in the exercise). 
I'd 
1. remove the exercise or
2. put some comment so user can easier figure it out (this pull request)
=> misleading excercise
